### PR TITLE
fix: add aceroconsumer back to conftest

### PR DESCRIPTION
**Pull request by richtia**
Adding back the AceroConsumer to conftest so it can be tested with

### CODE REVIEW

**Review by vibhatha — APPROVED** [review]
@richtia any specific reason why this was removed before?

**Comment by richtia** [comment]
> @richtia any specific reason why this was removed before?

Nothing other than Acero development stopping.

**Comment by vibhatha** [comment]
@richtia should we worry about these failed checks?

**Comment by vibhatha** [comment]
And @richtia Thanks for working on this very swiftly.

**Pull request merged**
